### ISSUE TITLE
how to use multiple sensors?

### ISSUE THREAD

**Issue by IIIdefconIII** [Paul-dH/Home-Assisant-Sensor-OvApi#10]
Hi, first of all, thanks for this awesome script, now my wife doesnt need to look at here phone each morning.

Im using this as the sensor codes but home assistant only shows Tram_23 properly cause there is no stop_code for the busses, is there a work around?

Bus 140
"RET_620_1":{"LineWheelchairAccessible":"UNKNOWN","TransportType":"BUS","DestinationName50":"Kralingse Zoom","DataOwnerCode":"RET","DestinationCode":"KZZM----","LinePublicNumber":"140","LinePlanningNumber":"620","LineName":"Kralingsezoom - Slikkerveer","LineDirection":1}
http://v0.ovapi.nl/line/RET_620_1
TimingPointCode":"31006183

Bus 183
RET_642_2":{"LineWheelchairAccessible":"UNKNOWN","TransportType":"BUS","DestinationName50":"Kralingsezoom via Keizerswaard","DataOwnerCode":"RET","DestinationCode":"BKZMKZZW","LinePublicNumber":"183","LinePlanningNumber":"642","LineName":"Kralingse Zoom - Zuidplein","LineDirection":2},
http://v0.ovapi.nl/line/RET_642_2
TimingPointCode":"31006177

```
###### SENSORS -----------------------------
sensor:
  - platform: ovapi
    name: Bus_140
    stop_code: 'null'
    route_code: '31006183'

  - platform: ovapi
    name: Bus_183
    stop_code: 'null'
    route_code: '31000227'

  - platform: ovapi
    name: Tram_23
    stop_code: '87'
    route_code: '31000227'

```
