### ISSUE TITLE
Create a passes filter for stops where more bus lines stop

### ISSUE THREAD

**Issue by Paul-dH** [Paul-dH/Home-Assisant-Sensor-OvApi#2]
See: http://v0.ovapi.nl/stopareacode/9501

At this stop 3 trams are stopping, there should be a filter possibility in the sensor config, like:

```
sensor:
  - platform: ovapi
    name: Tram_19
    stop_code: '9501'
    route_code: '32009501'
    pass_filter: _19_
```

The content of the fetched json looks like:
```
9501	
  32009501	
    Stop	
      Longitude	0.000000
      Latitude	00.00000
      TimingPointTown	"City"
      TimingPointName	"Stopname"
      TimingPointCode	"32009501"
      StopAreaCode	"9501"
      TimingPointWheelChairAccessible	"ACCESSIBLE"
      TimingPointVisualAccessible	"ACCESSIBLE"
    Passes
      HTM_20190111_2_20164_0
      HTM_20190111_6_60196_0
      HTM_20190111_19_190120_0
```

The filter should be applied to the items below and the content like `_19_`:

```
      HTM_20190111_2_20164_0
      HTM_20190111_6_60196_0
      HTM_20190111_19_190120_0
```
