### ISSUE TITLE
make more entities based on future: <number>

### ISSUE THREAD

**Issue by IIIdefconIII** [Paul-dH/Home-Assisant-Sensor-OvApi#24]
Hi Paul, we spoke before on Discord.
Currently i have a few entities so it will show like the picture below.
To improve the code is it possible to use a single entitie with a value of future: <number> that will automatically add the next few bus times?

Something like

```
entities:
        - entity: sensor.bus_140_templated
          icon: 'mdi:bus'
          future: 5

```

```
      columns: 5
      entities:
        - entity: sensor.bus_140_templated
          icon: 'mdi:bus'
        - entity: sensor.bus_140_future_1_templated
          icon: 'mdi:x'
        - entity: sensor.bus_140_future_2_templated
          icon: 'mdi:x'
        - entity: sensor.bus_140_future_3_templated
          icon: 'mdi:x'
        - entity: sensor.bus_140_future_4_templated
          icon: 'mdi:x'
      show_header_toggle: false
      show_name: false
      title: Bus 140
      type: glance
    cards: null
    style:
      background-image: url(/local/images/bus1.png?v=0.3)
    type: 'custom:card-modder'
```
