### ISSUE TITLE
Not seeing the instalation

### ISSUE THREAD

**Issue by maillme** [Paul-dH/Home-Assisant-Sensor-OvApi#38]
First - thanks for your work on this. 

So, 
I've followed the instructions. I placed the three files in the folder advised. I restarted HA Core. 
Then I tried to add this code to the config.yaml:

```
sensor:
  - platform: ovapi
    name: Tram_6
    stop_code: 9595
    route_code: 3200950
```

Bit, it gives me the following error when I try to restart the configurations yaml from supervisor: 

`Failed to call service homeassistant/reload_all. Cannot quick reload all YAML configurations because the configuration is not valid: Platform error sensor.ovapi - Integration 'ovapi' not found.`

Is there a step I am missing somewhere? 
thanks.
