### ISSUE TITLE
I can not see the sensor

### ISSUE THREAD

**Issue by maillme** [Paul-dH/Home-Assisant-Sensor-OvApi#39]
What are the things I should be looking at if i can not see the sensor in HA? 

I've added the files, and I added this code (to test it) to my config file - but, the sensor is not being read anywhere and isn;t in my list. I have restarted HA Core. 

Any help is greatly appreciated. 
Neil 

```
sensor:
  - platform: ovapi
    name: Tram_6
    stop_code: 9595
    route_code: 32009505
    show_future_departures: 4
```
